"""Ethereal DEX integration for perpetual futures trading."""

from vibe_quant.ethereal.archive import EtherealArchive
from vibe_quant.ethereal.data_client import (
    ETHEREAL_MAINNET_WS,
    ETHEREAL_TESTNET_WS,
    SYMBOL_MAP,
    SYMBOL_MAP_REVERSE,
    BookDepthCallback,
    BookDepthUpdate,
    EtherealChannel,
    EtherealDataClient,
    FundingRateCallback,
    FundingRateUpdate,
    MarketPriceCallback,
    MarketPriceUpdate,
    SubscriptionState,
    normalize_symbol,
    to_ethereal_symbol,
)
from vibe_quant.ethereal.execution_client import (
    ConfigurationError,
    EIP712OrderData,
    EtherealAPIError,
    EtherealConfig,
    EtherealExecutionClient,
    EtherealOrder,
    Fill,
    OrderResult,
    OrderSide,
    OrderStatus,
    OrderType,
    sign_order,
)
from vibe_quant.ethereal.ingestion import (
    ETHEREAL_ARCHIVE_BASE,
    ETHEREAL_TIMEFRAMES,
    archive_to_catalog,
    download_bars,
    download_funding_rates,
    get_ethereal_bar_type,
    ingest_all_ethereal,
    ingest_ethereal,
    ingest_ethereal_funding,
    klines_to_bars,
)
from vibe_quant.ethereal.instruments import (
    ETHEREAL_FUNDING_INTERVAL_SECS,
    ETHEREAL_INSTRUMENT_CONFIGS,
    ETHEREAL_VENUE,
    USDE,
    EtherealInstrumentConfig,
    create_ethereal_instrument,
    get_all_ethereal_instruments,
    get_ethereal_instrument,
    get_ethereal_symbols,
    get_max_leverage,
)
from vibe_quant.ethereal.venue import (
    ETHEREAL_FUNDING_INTERVAL,
    ETHEREAL_LATENCY_PRESETS,
    ETHEREAL_MAKER_FEE,
    ETHEREAL_TAKER_FEE,
    EtherealLatencyPreset,
    EtherealVenueConfig,
    get_ethereal_latency_model,
    get_ethereal_venue_for_backtesting,
    get_ethereal_venue_for_paper_trading,
)

__all__ = [
    # Ingestion
    "ETHEREAL_ARCHIVE_BASE",
    "ETHEREAL_TIMEFRAMES",
    "EtherealArchive",
    "archive_to_catalog",
    "download_bars",
    "download_funding_rates",
    "get_ethereal_bar_type",
    "ingest_all_ethereal",
    "ingest_ethereal",
    "ingest_ethereal_funding",
    "klines_to_bars",
    # Data Client
    "ETHEREAL_MAINNET_WS",
    "ETHEREAL_TESTNET_WS",
    "SYMBOL_MAP",
    "SYMBOL_MAP_REVERSE",
    "BookDepthCallback",
    "BookDepthUpdate",
    "EtherealChannel",
    "EtherealDataClient",
    "FundingRateCallback",
    "FundingRateUpdate",
    "MarketPriceCallback",
    "MarketPriceUpdate",
    "SubscriptionState",
    "normalize_symbol",
    "to_ethereal_symbol",
    # Execution Client
    "ConfigurationError",
    "EIP712OrderData",
    "EtherealAPIError",
    "EtherealConfig",
    "EtherealExecutionClient",
    "EtherealOrder",
    "Fill",
    "OrderResult",
    "OrderSide",
    "OrderStatus",
    "OrderType",
    "sign_order",
    # Instruments
    "ETHEREAL_FUNDING_INTERVAL_SECS",
    "ETHEREAL_INSTRUMENT_CONFIGS",
    "ETHEREAL_VENUE",
    "USDE",
    "EtherealInstrumentConfig",
    "create_ethereal_instrument",
    "get_all_ethereal_instruments",
    "get_ethereal_instrument",
    "get_ethereal_symbols",
    "get_max_leverage",
    # Venue
    "ETHEREAL_FUNDING_INTERVAL",
    "ETHEREAL_LATENCY_PRESETS",
    "ETHEREAL_MAKER_FEE",
    "ETHEREAL_TAKER_FEE",
    "EtherealLatencyPreset",
    "EtherealVenueConfig",
    "get_ethereal_latency_model",
    "get_ethereal_venue_for_backtesting",
    "get_ethereal_venue_for_paper_trading",
]
